
name: 'dora'
version: '1.0.0'

profile: default

models:
  'dora':
    +materialized: external
    staging:
      +materialized: view

on-run-start:
  - "{{ register_upstream_external_models() }}"

flags:
  send_anonymous_usage_stats: False