default:
  target: Exploration-dev
  outputs:
    Exploration-dev:
      type: duckdb
      path: "tmp.duckdb"
      external_root: "src/data/clean"
      schema: dev
      extensions:
        - parquet
config:
  send_anonymous_usage_stats: False